name: Terraform Lint
on: [push]

permissions:
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  tflint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '1.12.*'
          - '1.11.*'

    steps:
      - name: checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
#      - name: Cache plugin dir
#        uses: actions/cache@v4
#        with:
#          path: ~/.tflint.d/plugins
#          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
      - name: setup tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.58.0
#      - name: Init TFLint
#        run: tflint --init
#        env:
#          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
#          GITHUB_TOKEN: ${{ github.token }}
      - name: run tflint
        run: tflint -f compact --chdir terraform
